//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.EMS
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Event.
    /// </summary>
    // *** Start programmer edit section *** (Event CustomAttributes)

    // *** End programmer edit section *** (Event CustomAttributes)
    [AutoAltered()]
    [Caption("Мероприятие")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("EventE", new string[] {
            "Name as \'Название\'",
            "EventStartDate as \'Дата начала\'",
            "EventEndDate as \'Дата окончания\'",
            "Place as \'Место\'",
            "MaxNumberOfParticipants as \'Макс. число участников\'",
            "TicketPrice as \'Цена билета\'",
            "Organizer as \'Организатор\'",
            "Organizer.Name as \'Имя организатора\'"}, Hidden=new string[] {
            "Organizer.Name"})]
    [MasterViewDefineAttribute("EventE", "Organizer", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    [View("EventL", new string[] {
            "Name as \'Name\'",
            "EventStartDate as \'Дата начала\'",
            "EventEndDate as \'Дата окончания\'",
            "Place as \'Место\'",
            "MaxNumberOfParticipants as \'Макс. число участников\'",
            "TicketPrice as \'Цена билета\'",
            "Organizer.Name as \'Имя организатора\'"})]
    public class Event : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        private System.DateTime fEventStartDate;
        
        private System.DateTime fEventEndDate;
        
        private string fPlace;
        
        private int fMaxNumberOfParticipants;
        
        private int fTicketPrice;
        
        private IIS.EMS.Organizer fOrganizer;
        
        // *** Start programmer edit section *** (Event CustomMembers)

        // *** End programmer edit section *** (Event CustomMembers)

        
        /// <summary>
        /// EventEndDate.
        /// </summary>
        // *** Start programmer edit section *** (Event.EventEndDate CustomAttributes)

        // *** End programmer edit section *** (Event.EventEndDate CustomAttributes)
        public virtual System.DateTime EventEndDate
        {
            get
            {
                // *** Start programmer edit section *** (Event.EventEndDate Get start)

                // *** End programmer edit section *** (Event.EventEndDate Get start)
                System.DateTime result = this.fEventEndDate;
                // *** Start programmer edit section *** (Event.EventEndDate Get end)

                // *** End programmer edit section *** (Event.EventEndDate Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Event.EventEndDate Set start)

                // *** End programmer edit section *** (Event.EventEndDate Set start)
                this.fEventEndDate = value;
                // *** Start programmer edit section *** (Event.EventEndDate Set end)

                // *** End programmer edit section *** (Event.EventEndDate Set end)
            }
        }
        
        /// <summary>
        /// EventStartDate.
        /// </summary>
        // *** Start programmer edit section *** (Event.EventStartDate CustomAttributes)

        // *** End programmer edit section *** (Event.EventStartDate CustomAttributes)
        public virtual System.DateTime EventStartDate
        {
            get
            {
                // *** Start programmer edit section *** (Event.EventStartDate Get start)

                // *** End programmer edit section *** (Event.EventStartDate Get start)
                System.DateTime result = this.fEventStartDate;
                // *** Start programmer edit section *** (Event.EventStartDate Get end)

                // *** End programmer edit section *** (Event.EventStartDate Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Event.EventStartDate Set start)

                // *** End programmer edit section *** (Event.EventStartDate Set start)
                this.fEventStartDate = value;
                // *** Start programmer edit section *** (Event.EventStartDate Set end)

                // *** End programmer edit section *** (Event.EventStartDate Set end)
            }
        }
        
        /// <summary>
        /// MaxNumberOfParticipants.
        /// </summary>
        // *** Start programmer edit section *** (Event.MaxNumberOfParticipants CustomAttributes)

        // *** End programmer edit section *** (Event.MaxNumberOfParticipants CustomAttributes)
        public virtual int MaxNumberOfParticipants
        {
            get
            {
                // *** Start programmer edit section *** (Event.MaxNumberOfParticipants Get start)

                // *** End programmer edit section *** (Event.MaxNumberOfParticipants Get start)
                int result = this.fMaxNumberOfParticipants;
                // *** Start programmer edit section *** (Event.MaxNumberOfParticipants Get end)

                // *** End programmer edit section *** (Event.MaxNumberOfParticipants Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Event.MaxNumberOfParticipants Set start)

                // *** End programmer edit section *** (Event.MaxNumberOfParticipants Set start)
                this.fMaxNumberOfParticipants = value;
                // *** Start programmer edit section *** (Event.MaxNumberOfParticipants Set end)

                // *** End programmer edit section *** (Event.MaxNumberOfParticipants Set end)
            }
        }
        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (Event.Name CustomAttributes)

        // *** End programmer edit section *** (Event.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (Event.Name Get start)

                // *** End programmer edit section *** (Event.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (Event.Name Get end)

                // *** End programmer edit section *** (Event.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Event.Name Set start)

                // *** End programmer edit section *** (Event.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (Event.Name Set end)

                // *** End programmer edit section *** (Event.Name Set end)
            }
        }
        
        /// <summary>
        /// Place.
        /// </summary>
        // *** Start programmer edit section *** (Event.Place CustomAttributes)

        // *** End programmer edit section *** (Event.Place CustomAttributes)
        [StrLen(255)]
        public virtual string Place
        {
            get
            {
                // *** Start programmer edit section *** (Event.Place Get start)

                // *** End programmer edit section *** (Event.Place Get start)
                string result = this.fPlace;
                // *** Start programmer edit section *** (Event.Place Get end)

                // *** End programmer edit section *** (Event.Place Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Event.Place Set start)

                // *** End programmer edit section *** (Event.Place Set start)
                this.fPlace = value;
                // *** Start programmer edit section *** (Event.Place Set end)

                // *** End programmer edit section *** (Event.Place Set end)
            }
        }
        
        /// <summary>
        /// TicketPrice.
        /// </summary>
        // *** Start programmer edit section *** (Event.TicketPrice CustomAttributes)

        // *** End programmer edit section *** (Event.TicketPrice CustomAttributes)
        public virtual int TicketPrice
        {
            get
            {
                // *** Start programmer edit section *** (Event.TicketPrice Get start)

                // *** End programmer edit section *** (Event.TicketPrice Get start)
                int result = this.fTicketPrice;
                // *** Start programmer edit section *** (Event.TicketPrice Get end)

                // *** End programmer edit section *** (Event.TicketPrice Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Event.TicketPrice Set start)

                // *** End programmer edit section *** (Event.TicketPrice Set start)
                this.fTicketPrice = value;
                // *** Start programmer edit section *** (Event.TicketPrice Set end)

                // *** End programmer edit section *** (Event.TicketPrice Set end)
            }
        }
        
        /// <summary>
        /// Event.
        /// </summary>
        // *** Start programmer edit section *** (Event.Organizer CustomAttributes)

        // *** End programmer edit section *** (Event.Organizer CustomAttributes)
        [PropertyStorage(new string[] {
                "Organizer"})]
        [NotNull()]
        public virtual IIS.EMS.Organizer Organizer
        {
            get
            {
                // *** Start programmer edit section *** (Event.Organizer Get start)

                // *** End programmer edit section *** (Event.Organizer Get start)
                IIS.EMS.Organizer result = this.fOrganizer;
                // *** Start programmer edit section *** (Event.Organizer Get end)

                // *** End programmer edit section *** (Event.Organizer Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Event.Organizer Set start)

                // *** End programmer edit section *** (Event.Organizer Set start)
                this.fOrganizer = value;
                // *** Start programmer edit section *** (Event.Organizer Set end)

                // *** End programmer edit section *** (Event.Organizer Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "EventE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View EventE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("EventE", typeof(IIS.EMS.Event));
                }
            }
            
            /// <summary>
            /// "EventL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View EventL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("EventL", typeof(IIS.EMS.Event));
                }
            }
        }
    }
}
