//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.EMS
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Lessor.
    /// </summary>
    // *** Start programmer edit section *** (Lessor CustomAttributes)

    // *** End programmer edit section *** (Lessor CustomAttributes)
    [AutoAltered()]
    [Caption("Арендодатель")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("LessorE", new string[] {
            "Name as \'Имя\'",
            "Mail as \'Почта\'",
            "AvailableItems as \'Доступные предметы\'",
            "PhoneNumber as \'Телефонный номер\'",
            "AvailableRooms as \'Доступные помещения\'",
            "Password as \'Пароль\'",
            "Event as \'Мероприятие\'",
            "Event.Name as \'Имя меропрития\'"}, Hidden=new string[] {
            "Event.Name"})]
    [MasterViewDefineAttribute("LessorE", "Event", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    [View("LessorL", new string[] {
            "Name as \'Имя\'",
            "Mail as \'Почта\'",
            "AvailableItems as \'Доступные предметы\'",
            "PhoneNumber as \'Телефонный номер\'",
            "AvailableRooms as \'Доступные помещения\'",
            "Password as \'Пароль\'",
            "Event.Name as \'Имя мероприятия\'"})]
    public class Lessor : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        private string fMail;
        
        private string fAvailableItems;
        
        private decimal fPhoneNumber;
        
        private string fAvailableRooms;
        
        private string fPassword;
        
        private IIS.EMS.Event fEvent;
        
        // *** Start programmer edit section *** (Lessor CustomMembers)

        // *** End programmer edit section *** (Lessor CustomMembers)

        
        /// <summary>
        /// AvailableItems.
        /// </summary>
        // *** Start programmer edit section *** (Lessor.AvailableItems CustomAttributes)

        // *** End programmer edit section *** (Lessor.AvailableItems CustomAttributes)
        [StrLen(255)]
        public virtual string AvailableItems
        {
            get
            {
                // *** Start programmer edit section *** (Lessor.AvailableItems Get start)

                // *** End programmer edit section *** (Lessor.AvailableItems Get start)
                string result = this.fAvailableItems;
                // *** Start programmer edit section *** (Lessor.AvailableItems Get end)

                // *** End programmer edit section *** (Lessor.AvailableItems Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Lessor.AvailableItems Set start)

                // *** End programmer edit section *** (Lessor.AvailableItems Set start)
                this.fAvailableItems = value;
                // *** Start programmer edit section *** (Lessor.AvailableItems Set end)

                // *** End programmer edit section *** (Lessor.AvailableItems Set end)
            }
        }
        
        /// <summary>
        /// AvailableRooms.
        /// </summary>
        // *** Start programmer edit section *** (Lessor.AvailableRooms CustomAttributes)

        // *** End programmer edit section *** (Lessor.AvailableRooms CustomAttributes)
        [StrLen(255)]
        public virtual string AvailableRooms
        {
            get
            {
                // *** Start programmer edit section *** (Lessor.AvailableRooms Get start)

                // *** End programmer edit section *** (Lessor.AvailableRooms Get start)
                string result = this.fAvailableRooms;
                // *** Start programmer edit section *** (Lessor.AvailableRooms Get end)

                // *** End programmer edit section *** (Lessor.AvailableRooms Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Lessor.AvailableRooms Set start)

                // *** End programmer edit section *** (Lessor.AvailableRooms Set start)
                this.fAvailableRooms = value;
                // *** Start programmer edit section *** (Lessor.AvailableRooms Set end)

                // *** End programmer edit section *** (Lessor.AvailableRooms Set end)
            }
        }
        
        /// <summary>
        /// Mail.
        /// </summary>
        // *** Start programmer edit section *** (Lessor.Mail CustomAttributes)

        // *** End programmer edit section *** (Lessor.Mail CustomAttributes)
        [StrLen(255)]
        public virtual string Mail
        {
            get
            {
                // *** Start programmer edit section *** (Lessor.Mail Get start)

                // *** End programmer edit section *** (Lessor.Mail Get start)
                string result = this.fMail;
                // *** Start programmer edit section *** (Lessor.Mail Get end)

                // *** End programmer edit section *** (Lessor.Mail Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Lessor.Mail Set start)

                // *** End programmer edit section *** (Lessor.Mail Set start)
                this.fMail = value;
                // *** Start programmer edit section *** (Lessor.Mail Set end)

                // *** End programmer edit section *** (Lessor.Mail Set end)
            }
        }
        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (Lessor.Name CustomAttributes)

        // *** End programmer edit section *** (Lessor.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (Lessor.Name Get start)

                // *** End programmer edit section *** (Lessor.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (Lessor.Name Get end)

                // *** End programmer edit section *** (Lessor.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Lessor.Name Set start)

                // *** End programmer edit section *** (Lessor.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (Lessor.Name Set end)

                // *** End programmer edit section *** (Lessor.Name Set end)
            }
        }
        
        /// <summary>
        /// Password.
        /// </summary>
        // *** Start programmer edit section *** (Lessor.Password CustomAttributes)

        // *** End programmer edit section *** (Lessor.Password CustomAttributes)
        [StrLen(255)]
        public virtual string Password
        {
            get
            {
                // *** Start programmer edit section *** (Lessor.Password Get start)

                // *** End programmer edit section *** (Lessor.Password Get start)
                string result = this.fPassword;
                // *** Start programmer edit section *** (Lessor.Password Get end)

                // *** End programmer edit section *** (Lessor.Password Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Lessor.Password Set start)

                // *** End programmer edit section *** (Lessor.Password Set start)
                this.fPassword = value;
                // *** Start programmer edit section *** (Lessor.Password Set end)

                // *** End programmer edit section *** (Lessor.Password Set end)
            }
        }
        
        /// <summary>
        /// PhoneNumber.
        /// </summary>
        // *** Start programmer edit section *** (Lessor.PhoneNumber CustomAttributes)

        // *** End programmer edit section *** (Lessor.PhoneNumber CustomAttributes)
        public virtual decimal PhoneNumber
        {
            get
            {
                // *** Start programmer edit section *** (Lessor.PhoneNumber Get start)

                // *** End programmer edit section *** (Lessor.PhoneNumber Get start)
                decimal result = this.fPhoneNumber;
                // *** Start programmer edit section *** (Lessor.PhoneNumber Get end)

                // *** End programmer edit section *** (Lessor.PhoneNumber Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Lessor.PhoneNumber Set start)

                // *** End programmer edit section *** (Lessor.PhoneNumber Set start)
                this.fPhoneNumber = value;
                // *** Start programmer edit section *** (Lessor.PhoneNumber Set end)

                // *** End programmer edit section *** (Lessor.PhoneNumber Set end)
            }
        }
        
        /// <summary>
        /// Lessor.
        /// </summary>
        // *** Start programmer edit section *** (Lessor.Event CustomAttributes)

        // *** End programmer edit section *** (Lessor.Event CustomAttributes)
        [PropertyStorage(new string[] {
                "Event"})]
        [NotNull()]
        public virtual IIS.EMS.Event Event
        {
            get
            {
                // *** Start programmer edit section *** (Lessor.Event Get start)

                // *** End programmer edit section *** (Lessor.Event Get start)
                IIS.EMS.Event result = this.fEvent;
                // *** Start programmer edit section *** (Lessor.Event Get end)

                // *** End programmer edit section *** (Lessor.Event Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Lessor.Event Set start)

                // *** End programmer edit section *** (Lessor.Event Set start)
                this.fEvent = value;
                // *** Start programmer edit section *** (Lessor.Event Set end)

                // *** End programmer edit section *** (Lessor.Event Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "LessorE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View LessorE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("LessorE", typeof(IIS.EMS.Lessor));
                }
            }
            
            /// <summary>
            /// "LessorL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View LessorL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("LessorL", typeof(IIS.EMS.Lessor));
                }
            }
        }
    }
}
