//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.EMS
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Participant.
    /// </summary>
    // *** Start programmer edit section *** (Participant CustomAttributes)

    // *** End programmer edit section *** (Participant CustomAttributes)
    [AutoAltered()]
    [Caption("Участник")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ParticipantE", new string[] {
            "Name as \'Имя\'",
            "Mail as \'Почта\'",
            "PhoneNumber as \'Телефонный номер\'",
            "Password as \'Пароль\'",
            "Event as \'Мероприятие\'",
            "Event.Name as \'Название мероприятия\'"}, Hidden=new string[] {
            "Event.Name"})]
    [MasterViewDefineAttribute("ParticipantE", "Event", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    [View("ParticipantL", new string[] {
            "Name as \'Имя\'",
            "Mail as \'Почта\'",
            "PhoneNumber as \'Телефонный номер\'",
            "Password as \'Пароль\'",
            "Event.Name as \'Название мероприятия\'"})]
    public class Participant : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        private string fMail;
        
        private decimal fPhoneNumber;
        
        private string fPassword;
        
        private IIS.EMS.Event fEvent;
        
        // *** Start programmer edit section *** (Participant CustomMembers)

        // *** End programmer edit section *** (Participant CustomMembers)

        
        /// <summary>
        /// Mail.
        /// </summary>
        // *** Start programmer edit section *** (Participant.Mail CustomAttributes)

        // *** End programmer edit section *** (Participant.Mail CustomAttributes)
        [StrLen(255)]
        public virtual string Mail
        {
            get
            {
                // *** Start programmer edit section *** (Participant.Mail Get start)

                // *** End programmer edit section *** (Participant.Mail Get start)
                string result = this.fMail;
                // *** Start programmer edit section *** (Participant.Mail Get end)

                // *** End programmer edit section *** (Participant.Mail Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Participant.Mail Set start)

                // *** End programmer edit section *** (Participant.Mail Set start)
                this.fMail = value;
                // *** Start programmer edit section *** (Participant.Mail Set end)

                // *** End programmer edit section *** (Participant.Mail Set end)
            }
        }
        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (Participant.Name CustomAttributes)

        // *** End programmer edit section *** (Participant.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (Participant.Name Get start)

                // *** End programmer edit section *** (Participant.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (Participant.Name Get end)

                // *** End programmer edit section *** (Participant.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Participant.Name Set start)

                // *** End programmer edit section *** (Participant.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (Participant.Name Set end)

                // *** End programmer edit section *** (Participant.Name Set end)
            }
        }
        
        /// <summary>
        /// Password.
        /// </summary>
        // *** Start programmer edit section *** (Participant.Password CustomAttributes)

        // *** End programmer edit section *** (Participant.Password CustomAttributes)
        [StrLen(255)]
        public virtual string Password
        {
            get
            {
                // *** Start programmer edit section *** (Participant.Password Get start)

                // *** End programmer edit section *** (Participant.Password Get start)
                string result = this.fPassword;
                // *** Start programmer edit section *** (Participant.Password Get end)

                // *** End programmer edit section *** (Participant.Password Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Participant.Password Set start)

                // *** End programmer edit section *** (Participant.Password Set start)
                this.fPassword = value;
                // *** Start programmer edit section *** (Participant.Password Set end)

                // *** End programmer edit section *** (Participant.Password Set end)
            }
        }
        
        /// <summary>
        /// PhoneNumber.
        /// </summary>
        // *** Start programmer edit section *** (Participant.PhoneNumber CustomAttributes)

        // *** End programmer edit section *** (Participant.PhoneNumber CustomAttributes)
        public virtual decimal PhoneNumber
        {
            get
            {
                // *** Start programmer edit section *** (Participant.PhoneNumber Get start)

                // *** End programmer edit section *** (Participant.PhoneNumber Get start)
                decimal result = this.fPhoneNumber;
                // *** Start programmer edit section *** (Participant.PhoneNumber Get end)

                // *** End programmer edit section *** (Participant.PhoneNumber Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Participant.PhoneNumber Set start)

                // *** End programmer edit section *** (Participant.PhoneNumber Set start)
                this.fPhoneNumber = value;
                // *** Start programmer edit section *** (Participant.PhoneNumber Set end)

                // *** End programmer edit section *** (Participant.PhoneNumber Set end)
            }
        }
        
        /// <summary>
        /// Participant.
        /// </summary>
        // *** Start programmer edit section *** (Participant.Event CustomAttributes)

        // *** End programmer edit section *** (Participant.Event CustomAttributes)
        [PropertyStorage(new string[] {
                "Event"})]
        [NotNull()]
        public virtual IIS.EMS.Event Event
        {
            get
            {
                // *** Start programmer edit section *** (Participant.Event Get start)

                // *** End programmer edit section *** (Participant.Event Get start)
                IIS.EMS.Event result = this.fEvent;
                // *** Start programmer edit section *** (Participant.Event Get end)

                // *** End programmer edit section *** (Participant.Event Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Participant.Event Set start)

                // *** End programmer edit section *** (Participant.Event Set start)
                this.fEvent = value;
                // *** Start programmer edit section *** (Participant.Event Set end)

                // *** End programmer edit section *** (Participant.Event Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ParticipantE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ParticipantE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ParticipantE", typeof(IIS.EMS.Participant));
                }
            }
            
            /// <summary>
            /// "ParticipantL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ParticipantL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ParticipantL", typeof(IIS.EMS.Participant));
                }
            }
        }
    }
}
