




CREATE TABLE Organizer (
 primaryKey UUID NOT NULL,
 EventHost VARCHAR(255) NULL,
 EventPlan VARCHAR(255) NULL,
 Mail VARCHAR(255) NULL,
 Name VARCHAR(255) NULL,
 Password VARCHAR(255) NULL,
 PhoneNumber DECIMAL NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE Lessor (
 primaryKey UUID NOT NULL,
 AvailableItems VARCHAR(255) NULL,
 AvailableRooms VARCHAR(255) NULL,
 Mail VARCHAR(255) NULL,
 Name VARCHAR(255) NULL,
 Password VARCHAR(255) NULL,
 PhoneNumber DECIMAL NULL,
 Event UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE Event (
 primaryKey UUID NOT NULL,
 EventEndDate TIMESTAMP(3) NULL,
 EventStartDate TIMESTAMP(3) NULL,
 MaxNumberOfParticipants INT NULL,
 Name VARCHAR(255) NULL,
 Place VARCHAR(255) NULL,
 TicketPrice INT NULL,
 Organizer UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE Participant (
 primaryKey UUID NOT NULL,
 Mail VARCHAR(255) NULL,
 Name VARCHAR(255) NULL,
 Password VARCHAR(255) NULL,
 PhoneNumber DECIMAL NULL,
 Event UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMNETLOCKDATA (
 LockKey VARCHAR(300) NOT NULL,
 UserName VARCHAR(300) NOT NULL,
 LockDate TIMESTAMP(3) NULL,
 PRIMARY KEY (LockKey));


CREATE TABLE STORMSETTINGS (
 primaryKey UUID NOT NULL,
 Module VARCHAR(1000) NULL,
 Name VARCHAR(255) NULL,
 Value TEXT NULL,
 "User" VARCHAR(255) NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMAdvLimit (
 primaryKey UUID NOT NULL,
 "User" VARCHAR(255) NULL,
 Published BOOLEAN NULL,
 Module VARCHAR(255) NULL,
 Name VARCHAR(255) NULL,
 Value TEXT NULL,
 HotKeyData INT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMFILTERSETTING (
 primaryKey UUID NOT NULL,
 Name VARCHAR(255) NOT NULL,
 DataObjectView VARCHAR(255) NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMWEBSEARCH (
 primaryKey UUID NOT NULL,
 Name VARCHAR(255) NOT NULL,
 "Order" INT NOT NULL,
 PresentView VARCHAR(255) NOT NULL,
 DetailedView VARCHAR(255) NOT NULL,
 FilterSetting_m0 UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMFILTERDETAIL (
 primaryKey UUID NOT NULL,
 Caption VARCHAR(255) NOT NULL,
 DataObjectView VARCHAR(255) NOT NULL,
 ConnectMasterProp VARCHAR(255) NOT NULL,
 OwnerConnectProp VARCHAR(255) NULL,
 FilterSetting_m0 UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMFILTERLOOKUP (
 primaryKey UUID NOT NULL,
 DataObjectType VARCHAR(255) NOT NULL,
 Container VARCHAR(255) NULL,
 ContainerTag VARCHAR(255) NULL,
 FieldsToView VARCHAR(255) NULL,
 FilterSetting_m0 UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE UserSetting (
 primaryKey UUID NOT NULL,
 AppName VARCHAR(256) NULL,
 UserName VARCHAR(512) NULL,
 UserGuid UUID NULL,
 ModuleName VARCHAR(1024) NULL,
 ModuleGuid UUID NULL,
 SettName VARCHAR(256) NULL,
 SettGuid UUID NULL,
 SettLastAccessTime TIMESTAMP(3) NULL,
 StrVal VARCHAR(256) NULL,
 TxtVal TEXT NULL,
 IntVal INT NULL,
 BoolVal BOOLEAN NULL,
 GuidVal UUID NULL,
 DecimalVal DECIMAL(20,10) NULL,
 DateTimeVal TIMESTAMP(3) NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE ApplicationLog (
 primaryKey UUID NOT NULL,
 Category VARCHAR(64) NULL,
 EventId INT NULL,
 Priority INT NULL,
 Severity VARCHAR(32) NULL,
 Title VARCHAR(256) NULL,
 Timestamp TIMESTAMP(3) NULL,
 MachineName VARCHAR(32) NULL,
 AppDomainName VARCHAR(512) NULL,
 ProcessId VARCHAR(256) NULL,
 ProcessName VARCHAR(512) NULL,
 ThreadName VARCHAR(512) NULL,
 Win32ThreadId VARCHAR(128) NULL,
 Message VARCHAR(2500) NULL,
 FormattedMessage TEXT NULL,
 PRIMARY KEY (primaryKey));



 ALTER TABLE Lessor ADD CONSTRAINT FK6690bc746ed57488d3caf4fd8b160377ca1e1c90 FOREIGN KEY (Event) REFERENCES Event; 
CREATE INDEX Index6690bc746ed57488d3caf4fd8b160377ca1e1c90 on Lessor (Event); 

 ALTER TABLE Event ADD CONSTRAINT FKe4249b777570262b9b4db608149b04b30749d2ee FOREIGN KEY (Organizer) REFERENCES Organizer; 
CREATE INDEX Indexe4249b777570262b9b4db608149b04b30749d2ee on Event (Organizer); 

 ALTER TABLE Participant ADD CONSTRAINT FKbb692e4d3d06341ba6c1913ac312cf558bf8c94c FOREIGN KEY (Event) REFERENCES Event; 
CREATE INDEX Indexbb692e4d3d06341ba6c1913ac312cf558bf8c94c on Participant (Event); 

 ALTER TABLE STORMWEBSEARCH ADD CONSTRAINT FKc4378e39870eb056aec84088683297a01d2a6200 FOREIGN KEY (FilterSetting_m0) REFERENCES STORMFILTERSETTING; 

 ALTER TABLE STORMFILTERDETAIL ADD CONSTRAINT FK921d16269835017e2a0d0e29ad6fb175454a70d0 FOREIGN KEY (FilterSetting_m0) REFERENCES STORMFILTERSETTING; 

 ALTER TABLE STORMFILTERLOOKUP ADD CONSTRAINT FKce38ef0db3f01a53acaa49fed8853fb941ad47ba FOREIGN KEY (FilterSetting_m0) REFERENCES STORMFILTERSETTING; 

